CREATE TABLE IF NOT EXISTS orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100)   NOT NULL,
    amount        NUMERIC(12, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    updated_at    TIMESTAMP
);
